### ISSUE TITLE
Change from using RCurl to httr

### ISSUE THREAD

**Issue by phillc73** [phillc73/abettor#11]
The httr provides a much nicer and easier to user interface than RCurl. I'd like to change this package to use httr rather than RCurl.

See `backblazer` package for example:
https://github.com/phillc73/backblazer/blob/master/R/b2AuthorizeAccount.R

**Comment by phillc73** [comment]
loginBF() and keepAlive() functions updated to httr.  Thanks to input from @willtudorevans @bcaneco on issue #21

**Comment by freddiec** [comment]
loginBF function works fine using httr package instead of RCurl. Is there any chance of changing the logoutBF function to use httr as well?

**Comment by phillc73** [comment]
@freddiec Yes, for sure I can look at converting that function next. I'm traveling for a few days, but will aim to do it next week.

**Comment by freddiec** [comment]
Brilliant, much appreciated.

**Comment by freddiec** [comment]
Did you find time to take a look at converting the logoutBF() function to use httr instead of RCurl ? Betfair no longer recognises the original version. .Thanks.

**Comment by thewetdog** [comment]
@freddiec - the following might help you with logging out.

```
alternativeLogoutBF <- function(suppress = TRUE, sslVerify = TRUE){
  if(suppress){
    logout <- suppressWarnings(
      as.list(
        httr::content(
          httr::POST(
            url = "https://identitysso.betfair.com/api/logout", config = httr::config(ssl_verifypeer = sslVerify),
            httr::add_headers(
              Accept = "application/json",
              `X-Application` = Sys.getenv("product"),
              `X-Authentication` = Sys.getenv("token"),
              `Content-Type` = "application/json"
            )
          )
        )
      )
    )
  } else(
    logout <- as.list(
      httr::content(
        httr::POST(
          url = "https://identitysso.betfair.com/api/logout", config = httr::config(ssl_verifypeer = sslVerify),
          httr::add_headers(
            Accept = "application/json",
            `X-Application` = Sys.getenv("product"),
            `X-Authentication` = Sys.getenv("token"),
            `Content-Type` = "application/json"
          )
        )
      )
    )
  )
  return(paste0(logout$status, ":", logout$error))
}
```

**Comment by freddiec** [comment]
Hi wetdog,Worked an absolute treat. Thank you very much for your help, you're a star !Regards,freddiec  -----Original Message-----

**Comment by phillc73** [comment]
Done, thanks to @Soccerama
