### ISSUE TITLE
Limit_on_close

### ISSUE THREAD

**Issue by Tammboy** [phillc73/abettor#18]
Hi,

I seem to be getting bet failures when using the limit on close functionality:

Back bet example at BSP which is working well
placeOrders(
marketId=nmarketId,
selectionId=nselectionId,betSide="BACK",
betSize=2,
reqPrice="1.01",
betType="MARKET_ON_CLOSE",
persistenceType="MARKET_ON_CLOSE",
customerRef=nref,
sslVerify=FALSE)

Lay bet example at BSP which is limit on close and is not working - have i got syntax wrong at all?
placeOrders(
marketId=nmarketId,
selectionId=nselectionId,
betSide="LAY",
betSize=nstake,
reqPrice="5.00",
betType="LIMIT_ON_CLOSE",
customerRef=nref,
sslVerify=FALSE)

Many thanks

Jake.

**Comment by phillc73** [comment]
@Tammboy Apologies for the delay replying. I haven't had a chance to look at this issue, or your comment on #7 

I will try to find the time to do so in the coming week or so.

I am still using this package in production, not to place bets, but to retrieve Betfair horse racing prices and results on a daily basis.

**Comment by Tammboy** [comment]
Hey Phil,

Yes it's a fantastic package and I use it every day. It'd just be great if we could get the limit price part to work on the back/lay side when posting bets at BSP as well.

Many thanks,

Jake

Sent from my iPhone

On 9 Mar 2017, at 06:53, Phill <notifications@github.com<mailto:notifications@github.com>> wrote:


@Tammboy<https://github.com/Tammboy> Apologies for the delay replying. I haven't had a chance to look at this issue, or your comment on #7<https://github.com/phillc73/abettor/issues/7>

I will try to find the time to do so in the coming week or so.

I am still using this package in production, not to place bets, but to retrieve Betfair horse racing prices and results on a daily basis.

**Comment by Soccerama** [comment]
Found a link - see below. Here are the minimum bet sizes for each currency. A bsp liability of 5 is below the minimum for all currencies so that is why this bet would be failing. Same goes for issue #22 where the bsp liability is 2. 

https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/Additional+Information#AdditionalInformation-CurrencyParameters

**Comment by phillc73** [comment]
As far as I can see the function works as intended within the limits of Betfair rules. Thanks @Soccerama for investigating.
