### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by bcaneco** [phillc73/abettor#21]
Hi,

Yesterday I started getting this error at login:

```
> loginBF(username = user, password = pass, applicationKey = appKey)
<SSL_CONNECT_ERROR in function (type, msg, asError = TRUE) {    if (!is.character(type)) {        i = match(type, CURLcodeValues)  typeName = if (is.na(i))   character()  else names(CURLcodeValues)[i]    }    typeName = gsub("^CURLE_", "", typeName)    fun = (if (asError)    stop  else warning)    fun(structure(list(message = msg, call = sys.call()), class = c(typeName,   "GenericCurlError", "error", "condition")))}(35L, "error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol",     TRUE): error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol>
Error in function (type, msg, asError = TRUE)  : 
  error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

Is this related with Betfair's recent change in communications security settings, allowing only TLS 1.2 protocols? 

This is the email I got from Betfair, on 01/02/2019.

>Subject: Betfair API - TLS 1.2 - from 7th February 2019
(...)
Please be aware that from 7th February, the only protocol for securing the communication between Betfair servers and web browsers at login will be TLS 1.2. Older versions (TLS.1.0, TLS.1.1 or SSLv3) will no longer work.
Although we don't expect this to have an impact on API clients we'd recommend that you refer to the following resources depending on your programming language/framework to confirm that your using TLS 1.2 or above:
(...)

My current version of RCurl appears to be using an older protocol
``` 
> RCurl::curlVersion()$ssl_version
[1] "OpenSSL/1.0.0o"
```

Is there a quick fix to this? 

Thank you!

**Comment by JJHeathview** [comment]
Hi Phil,
I trust you are well.

had the same problem, and the same error message.

I found this on Stackoverflow regarding TLS protocols and RCurl(), it may be of use : https://stackoverflow.com/questions/38130293/tls-v1-1-tls-v1-2-support-in-rcurl


Best Wishes,
Jason Hathorn


________________________________

**Comment by willtudorevans** [comment]
Also having the same problem on Windows, Mac OS seems to work fine still.

**Comment by willtudorevans** [comment]
I built this function as a replacement for ```loginBF``` which I think solves the issue.
```
logBF <- function(username, password, applicationKey, sslVerify = T) {
  credentials <- paste0("username=", username, "&password=", password)
  loginReturn <- httr::POST(url = "https://identitysso.betfair.com/api/login", config = httr::config(ssl_verifypeer = T),
                            query = credentials, 
                            httr::add_headers(Accept = "application/json", `X-Application` = applicationKey))
  authenticationKey <- httr::content(loginReturn)
  Sys.setenv(product = authenticationKey$product)
  Sys.setenv(token = authenticationKey$token)
  return(paste0(authenticationKey$status, ":", authenticationKey$error))
}
```

**Comment by statsgeeknz** [comment]
@willtudorevans - legend. Thanks

**Comment by phillc73** [comment]
Thanks everyone for reporting this issue. It's a pleasant surprise to see this package still has some love!

Especially thanks to @willtudorevans for the replacement function. If @JJHeathview and @bcaneco can confirm this resolves the problem, I will update the function within the package.

**Comment by bcaneco** [comment]
Yes, @willtudorevans absolutely smashed this issue in pieces! Thank you!

The KeepAlive() function also requires updating. The following replacement function seems to do the trick.

```
kpAlive <- function (suppress = TRUE, sslVerify = TRUE) 
{
  product <- Sys.getenv("product")
  token <- Sys.getenv("token")
  
  if (suppress){
    keepAlive <- suppressWarnings(httr::content(
          httr::POST(url = "https://identitysso.betfair.com/api/keepAlive", config = httr::config(ssl_verifypeer = sslVerify),
                     httr::add_headers(Accept = "application/json", `X-Application` = product, 
                                       `X-Authentication` = token, `Content-Type` = "application/json"))
      )
    )
  }else{
    keepAlive <- httr::content(
        httr::POST(url = "https://identitysso.betfair.com/api/keepAlive", config = httr::config(ssl_verifypeer = sslVerify),
                   httr::add_headers(Accept = "application/json", `X-Application` = product, 
                                     `X-Authentication` = token, `Content-Type` = "application/json")
      )
    )
  }

  return(paste0(keepAlive$status, ":", keepAlive$error))
}
```


Thanks for keeping this very useful package going Phil.

Cheers

**Comment by phillc73** [comment]
Thanks @bcaneco, I'll update that function too.

To be honest, I haven't done anything to keep the package going in some time. I appreciate everyone's feedback and enhancement suggestions. They actually provide me some motivation to spend time working on this.

**Comment by JJHeathview** [comment]
Hi,
Yes, the new function works for me, SUCCESS: returned.

Many thanks, much appreciated , it's a cool package, great you still maintain it.
Regards,
Jason Hathorn



________________________________

**Comment by CronoxBC** [comment]
The function above isn't working for me on my Windows VPS, it just hangs and if I stop the process it returns:
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Operation was aborted by an application callback

Any ideas??

**Comment by thewetdog** [comment]
Hi, I was wondering if this has to deal with logging issues / time out. I am running the following:

```
eventID <- 29212093 #could be any id
MarketCatalogue <- listMarketCatalogue(
    eventTypeIds = 1,
    eventIds = eventID,
    marketTypeCodes = "MATCH_ODDS"
)
```
So far so good. The following gives me issues at times:
```
listMarketBook(marketIds = MarketCatalogue$marketId[1], priceData = "EX_ALL_OFFERS")
```
I run listMarketBook as above and it returns data as expected. I re-run it after a few seconds and it returns an empty data frame. Running it again after a while and data is there again. Any pointers to why this is happening?

Additionally, I sometimes run into this error:
```
Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to api.betfair.com port 443: Timed out
```
I am using "logBF" function as provided by @willtudorevans. I have read that this error is related to proxy authentication but I have no clue how to go about it.

Thanks for any pointers.

**Comment by phillc73** [comment]
@thewetdog As noted by @bcaneco the keepAlive() function also requires updating. Perhaps this will solve your issue. 

I am planning on updating the package this week (truly I hope so) with these enhanced functions.

**Comment by phillc73** [comment]
Please test the updated loginBF() and keepAlive() functions. I'll close this Issue now, but happen to re-open if problem persists.
