### ISSUE TITLE
Lay Starting Price Error

### ISSUE THREAD

**Issue by Timmyy22** [phillc73/abettor#22]
Laying on a horse with starting price like this

placeOrders(
    marketId = market_id,
    selectionId =  runners[1,]$selectionId,
    betSide = "LAY",
    betSize = "2",
    betType  = "MARKET_ON_CLOSE"
  )

throws the error "INVALID_BET_SIZE". Backing the horse runs normally. I read that another person in 2017 had the same problem, but I already updated the newest version...

**Comment by phillc73** [comment]
Apologies it's taken me a while to reply. Unfortunately, the reply is to say that I don't have an answer for you. I haven't had a chance to look at this library for a while, nor this specific bug. I will try to do so in the coming weeks.

**Comment by Soccerama** [comment]
While researching something else today I found this in the rules & regulations:
"The minimum liability for a bet placed at Betfair SP is £10 for a lay bet and £2 for a back bet (or the currency equivalent in each case)."
It was in section "9. Rules for Betfair Starting Price".
So, `abettor` was behaving correctly in rejecting this bet as it was below the minimum BSP liability size. Based on this information, both this issue and issue #18 can be closed.

**Comment by phillc73** [comment]
As far as I can see the function works as intended within the limits of Betfair rules. Thanks @Soccerama for investigating.
