### ISSUE TITLE
Abettor not installing package in R version 4

### ISSUE THREAD

**Issue by Markov12345** [phillc73/abettor#23]
Hello,
              Ive just upgraded toR Version r and when I try to reinstall the abbettpr package it tells me its not available for R version 4. Can this ne fixed as I need R version 4.

**Comment by roseypro** [comment]
Is there update?

**Comment by phillc73** [comment]
Sorry, no update. I haven't installed R version 4 anywhere in order to test. I'm pretty sure it'll be a dependency issue somewhere though.

**Comment by roseypro** [comment]
Thanks for reply Phill. Wasn't sure if the package was still maintained and working.


-------- Original message --------

**Comment by roseypro** [comment]
Is that something I can fix or would I be better off rolling back a version? Thanks Phill

Chris


-------- Original message --------

**Comment by phillc73** [comment]
I guess the answer is that the package is barely maintained and it still works against the R versions I've tested it against, which sadly doesn't include v4.0. As sport and racing in general are shut down at the moment, I haven't been using the package in anger for a few months either.

I honestly can't say when I'll upgrade to R v4.0 and have a chance to test the package. Rolling back might be a better short term option.

One thing you could do to assist, could be to extract the individual functions from the package, starting with [loginBF](https://github.com/phillc73/abettor/blob/master/R/loginBF.R) and then trying perhaps [listCountries](https://github.com/phillc73/abettor/blob/master/R/listCountries.R) and executing them manually. Load the three libraries, `RCurl`, `httr` and `jsonlite` manually at the start.

If those functions continue to work with R v4.0, I'll need to dig deeper.

**Comment by roseypro** [comment]
Sure I'll give it a go.

Thanks again for the assistance.


-------- Original message --------

**Comment by Markov12345** [comment]
Hi,
       Thanks for the reply. I've extracted the functions and they do still
work. So Im just using them at present. The issues may just be fixed by
repackaging the functions for version 4. Racing is still on in Australia so
Im still running the code.

**Comment by phillc73** [comment]
Good news! 

I'll have a look at re-packaging over the weekend if I can.

**Comment by roseypro** [comment]
Hi both, the package installed for me today. Think it's because I didn't have devtools installed previously. May not even need a repackage!
I used install_git.


-------- Original message --------
