### ISSUE TITLE
increase getAccountStatement limit above 100 records

### ISSUE THREAD

**Issue by Soccerama** [phillc73/abettor#29]
The maximum number of records that can be returned from an API call is 100. This means users of this function have to use the function repetitively to get their full account statement. It would be preferable if the function handled this and returned all available records as the default.

I have written some code to address this and will do a pull request in the next day or so.

**Comment by phillc73** [comment]
Looked good to me and worked with my initial testing. Thank you! 

If you're motivated, there's a lot more API functions which could be written. Let me know if you decide to work on anything, so we're not building the same things!

**Comment by Soccerama** [comment]
I'm happy to have a go at writing some more functions if you're happy to share your thoughts. I'm not currently working on anything for this repo and no specific ideas.
