### ISSUE TITLE
Additional Betting API Calls

### ISSUE THREAD

**Issue by phillc73** [phillc73/abettor#33]
The following Betting API calls are not yet supported by `abettor` and probably could/should be:

-  [ ] <strike>[listClearedOrders](https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/listClearedOrders)</strike>
- [x] [listRunnerBook](https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/listRunnerBook)
- [x] [listTimeRanges](https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/listTimeRanges)
- [ ] placeOrder, support for [Spanish](https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/Betting+on+Spanish+Exchange) and [Italian](https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/Betting+On+Italian+Exchange) exchange betting

**Comment by Soccerama** [comment]
Phill, 

I'm happy to have a go at these. With `listClearedOrders` it seems to already be there. Are you looking for refinements to it?

**Comment by phillc73** [comment]
@Soccerama No, just couldn't see the wood for the trees. I'll remove `listClearedOrders`

**Comment by Soccerama** [comment]
Phill, The new functions are added and the remaining task relates to adding new exchanges. My reading of the API documentation suggests that the login process to the Spanish and Italy exchanges is different and after that all API calls are the same - and to the UK exchange. 
Would it be better to close this issue and open a new one with a more specific title around the exchange login?

**Comment by phillc73** [comment]
@Soccerama Agreed.
