### ISSUE TITLE
Additional Accounts API Calls

### ISSUE THREAD

**Issue by phillc73** [phillc73/abettor#36]
The following Accounts API calls exist, but are not yet supported by `abettor`. Package should be updated to include them.

- [ ] <strike>[createDeveloperAppKeys](https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/createDeveloperAppKeys)</strike>
- [ ] <strike>[getDeveloperAppKeys](https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/getDeveloperAppKeys)</strike>
- [ ] <strike>[getAccountFunds](https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/getAccountFunds)</strike>
- [x] [getAccountDetails](https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/getAccountDetails)
- [x] [listCurrencyRates](https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/listCurrencyRates)

**Comment by Soccerama** [comment]
`getAccountFunds `is already there as `checkBalance`

**Comment by phillc73** [comment]
@Soccerama Well spotted. Can't remember why I changed the name of that now.

**Comment by Soccerama** [comment]
Have added getAccountDetails function. (It's getAccountFunds that was already there as checkBalance).

Now working on listCurrencyRates

**Comment by phillc73** [comment]
Relevant account related calls added.
