### ISSUE TITLE
Error in download(dest, src, auth) : client error: (404) Not Found

### ISSUE THREAD

**Issue by TheGeekAndI** [phillc73/abettor#4]
Hi @phillc73 ,

I am currently trying to build a betfair app and have come across your package. I am trying to download install the package according to the README file. 

I am running Windows 7 64-bit and have installed Rtools v3.1

The code I am looking to run and the response is as follows

```R
> devtools::install_github('phillc73/abbetor')
Downloading github repo phillc73/abbetor@master
Error in download(dest, src, auth) : client error: (404) Not Found
```

Are you able to help me to download the package?

Many thanks!

**Comment by phillc73** [comment]
Happy to help.

You have a typo in the package name. Try:

```
devtools::install_github("phillc73/abettor")
```
Two 't's and one 'b', not the other way around.

The package could probably do with some love at the moment, as I haven't made any updates for a while now. Although I can confirm everything should still work. I have a script in production which pulls pricing data every day and it's working fine.

Let me know if there's anything else I can assist with.

**Comment by TheGeekAndI** [comment]
Hi @phillc73 thank you so much for the quick response for such a simple query! Worked a treat. I'll have a go with your package and let you know if I need help with anything else. Cheers!
