### ISSUE TITLE
Rename checkBalance and listMarketPandL Functions

### ISSUE THREAD

**Issue by phillc73** [phillc73/abettor#44]
The functions `checkBalance` and `listMarketPandL` should be renamed to match the naming convention used in the Betfair API calls, for consistency with the rest of the library.

Specifically that is:

- `checkBalance` to `getAccountFunds`
- `listMarketPandL` to `listMarketProfitAndLoss`

Old function names should re-direct to new function names for backwards compatibility.

**Comment by Soccerama** [comment]
Completely agree with this proposed change and had thought the same thing myself. My only reservation was the backwards issue but a simple redirect should manage that.

**Comment by phillc73** [comment]
Completed with commit https://github.com/phillc73/abettor/commit/19f6688ffb255a6f173acaabd25d37218790eaed
