### ISSUE TITLE
Minor issue when trying to cancel individual betIds. Simple code fix has been proposed.

### ISSUE THREAD

**Issue by Soccerama** [phillc73/abettor#61]

**Comment by Soccerama** [comment]
Okay, I thought I'd tested this and it worked but now I'm not sure. Will do some more testing here to ensure it is right.

**Comment by Soccerama** [comment]
Updated code changes which have been tested and should fix the problem and be robust.

**Comment by phillc73** [comment]
Merged. Hopefully should be fixed :-) Thank you!
