### ISSUE TITLE
Get historical non-sports data

### ISSUE THREAD

**Issue by saywhatsaywah** [phillc73/abettor#71]
Hello all,

I've used the library to find the eventTypeIDs and competitionID I need, which are 2378961 and 11339499 respectively. But I can't seem to get historical data for them. I would have thought that Betfair would provide this under 'Other Sports' but I guess that isn't the case.

Ideally, I'd like historical data for them going back to the beginning of this year.

If anyone has any pointers that would be really appreciated. Thank you!

**Comment by Soccerama** [comment]
We've never actually built out the functionality to grab all of the historical data. As you can see, it is still on the issues list. 
I get historical data from here: https://historicdata.betfair.com/#/home
